### ISSUE TITLE
GCS can be slow to connect to SITL (30+ seconds first time)

### ISSUE THREAD

**Issue by brucecrevensten** [arctic-fire-development/dapper-gcs#504]
The GCS seems to miss connecting to the SITL for the first time, every time.  Something in the UAVConnectionManager either needs to wait or retry for a while, possibly as the APM is booting…?  It gets hung up here:

```
2015-03-18T17:15:22.776Z - silly: establishing MAVLink connection... ifAttach=false
```

Refreshing the page doesn't fix it.  Kicking the node *server* does fix it.  Need more careful debugging steps.

**Comment by brucecrevensten** [comment]
Turned out, it's not failing to connect, I'm just not patient.

Timed it and it took 36 seconds, but it connected normally.  ??  Maybe this is just a SITL artefact.  Need to test on the IRIS.

**Comment by rayjanwilson** [comment]
connection is crazy fast over serial radio link. this must be a sitl thing.

the gist below is a log file with silly debug turned on

https://gist.github.com/e0692d26db23afc71af2.git
