### ISSUE TITLE
Many STATUSTEXT notifications are not relevant and should be suppressed

### ISSUE THREAD

**Issue by brucecrevensten** [arctic-fire-development/dapper-gcs#515]
This is especially noticeable after going to APM3.2.

**Comment by brucecrevensten** [comment]
xref #426

**Comment by brucecrevensten** [comment]
xref #524

**Comment by brucecrevensten** [comment]
The biggest offender here is the `STATUSTEXT` messages.  Those need to be filtered in `app/views/GlobalGui.js`.

**Comment by brucecrevensten** [comment]
The pot of gold search term in APM source for for these is `gcs_send_text_P`.

**Comment by rayjanwilson** [comment]
weird, some of the growlType are booleans

![screen shot 2015-04-29 at 4 24 44 pm](https://cloud.githubusercontent.com/assets/238897/7404219/59b7674e-ee8c-11e4-9241-da0238fd2199.png)

**Comment by rayjanwilson** [comment]
changed code logic to be 'false' === growlType

**Comment by rayjanwilson** [comment]
added a bunch more STATUSTEXT messages

keep running into some weird hiccup where the gcs server resets. will have to look into it tomorrow

**Comment by rayjanwilson** [comment]
gcs server is not resetting today. weird.

**Comment by rayjanwilson** [comment]
ok going to clean up the console.logs and push

**Comment by rayjanwilson** [comment]
oh snap, there's also a function in ardupilot called `send_text_P` that sends messages via STATUSTEXT.

one message was `flight plan received`

**Comment by rayjanwilson** [comment]
ok added `flight plan received` to the regex list. pushed what i have for now
