### ISSUE TITLE
Change GROUND START status text / growl message to be more meaningful

### ISSUE THREAD

**Issue by brucecrevensten** [arctic-fire-development/dapper-gcs#550]
It sounds like it means that it's going to start on the ground but it happens way before flight.  What is happening there?  Change the message to something else.

**Comment by rayjanwilson** [comment]
dunno. i'll add the ability to alter the message if we want.

**Comment by brucecrevensten** [comment]
In `ArduCopter/system.pde` we have: "This function does all the calibrations, etc. that we need during a ground start".  So the message here should be changed to read "System is performing ground calibrations" instead of "GROUND START".
