### ISSUE TITLE
Load + confirm Paths revision on GCS units for flight testing, pair radios, and ready for flight

### ISSUE THREAD

**Issue by brucecrevensten** [arctic-fire-development/dapper-gcs#569]
Also need to pre-cache maps for Kunkel field.

**Comment by rayjanwilson** [comment]
#### Steps
- set wifi to Client mode
- `git pull`
- verify sha
  - `git log --oneline`
- `grunt`
- browse to gcsXX.local
  - grab maps for soccer field
- set client to AP mode
- reboot
- verify AP is up

SHA verify
- GCS01
 - a860df1753140f3efe9dbafe98e3305aea3cb79e
- GCS03
  - a860df1753140f3efe9dbafe98e3305aea3cb79e
- GCS04
  - a860df1753140f3efe9dbafe98e3305aea3cb79e

**Comment by rayjanwilson** [comment]
next i need to:
- ensure the radios are correctly defined in `config.json`
- ensure the radios are paired with the iris+

**Comment by rayjanwilson** [comment]
complete
