### ISSUE TITLE
mavlink.js does not appear to be installed correctly on gcs hardware

### ISSUE THREAD

**Issue by rayjanwilson** [arctic-fire-development/dapper-gcs#579]
on the gcs box
`node -v`
`v0.10.32`

`npm -v`
`2.7.6`

dapper-gcs sha
- a860df1753140f3efe9dbafe98e3305aea3cb79e

package.json has
"mavlink_ardupilotmega_v1.0": "file:./etc/mavlink_ardupilotmega_v1.0.tgz"

however the mavlink installed into node_modules looks like it's from the npm online repo

**Comment by rayjanwilson** [comment]
updated npm to 2.9
deleted node_modules
ran a fresh `npm install`
verified the installed mavlink.js is from the tarball
ran a fresh grunt
restarted the dapper-gcs.service
connected to gcs03.local
was able to connect to the iris

![screen shot 2015-05-06 at 1 28 23 am](https://cloud.githubusercontent.com/assets/238897/7490754/981dd074-f38f-11e4-9c9f-8670cc5270d7.png)

**Comment by brucecrevensten** [comment]
Great!  Let's make a checklist/spreadsheet/some other documentation to lock down the install procedure for this so that we have a way to ensure that a given box is built out correctly, something we can run through in the office before going to do a flight.

**Comment by rayjanwilson** [comment]
should be able to close now
