### ISSUE TITLE
gcs.log did not behave as expected

### ISSUE THREAD

**Issue by rayjanwilson** [arctic-fire-development/dapper-gcs#580]
does not appear to be logging in debug or silly mode

**Comment by brucecrevensten** [comment]
It should be doing these things:

 * logging at the correct environmental level
 * appending to the same log file each time

Need to verify what is happening before test flight.

**Comment by rayjanwilson** [comment]
this is the same thing that happened in #637. once the logging was moved outside the /home directory to /var/log, everything was writing successfully.
