### ISSUE TITLE
Repair parameter matching code failing due to terminating nulls

### ISSUE THREAD

**Issue by brucecrevensten** [arctic-fire-development/dapper-gcs#609]
![screen shot 2015-05-14 at 10 45 55 am](https://cloud.githubusercontent.com/assets/525049/7658251/0c119662-fae5-11e4-9c37-cfd6cd94fc82.png)

`2015-03-16T19:24:07.678Z - silly: Ignoring verification because parameter names did not match [SYSID_THISMAV] [SYSID_THISMAV]`

It looks like we may need to strip the symbols seen as `^@` here.

**Comment by rayjanwilson** [comment]
i added a util.inspect(msg.param_id) and was able to see for sure it's unicode null (\u0000) that needs to be trimmed out.

after adding a trim() function taken from lodash, we get this:

![screen shot 2015-05-15 at 4 16 51 pm](https://cloud.githubusercontent.com/assets/238897/7663801/dfda98e4-fb1d-11e4-838b-d0884e25f570.png)

so the issue with hidden unicode characters has been taken care of. 

i'm gonna clean out the extra logging and submit pull request.
